llm:
  provider: OPENAI
  meta:
    model: gpt-4o-mini
    max_tokens: 15000
    temperature: 0.3
  http_client:
    timeout: 120
    api_url: https://api.openai.com/v1

vcs:
  provider: GITHUB
  http_client:
    api_url: https://api.github.com
    timeout: 120

prompt:
  inline_prompt_files: [ ./prompts/inline.md ]
  context_prompt_files: [ ./prompts/inline.md ]
  summary_prompt_files: [ ./prompts/summary.md ]

review:
  dry_run: false
