app_url=https://nikita-filonov.github.io/qa-automation-engineer-ui-course
headless=True
browsers=[<Browser.CHROMIUM: 'chromium'>]
test_user={'email': 'user.name@gmail.com', 'username': 'username', 'password': 'password'}
test_data={'image_png_file': WindowsPath('testdata/files/image.png')}
videos_dir=videos
tracing_dir=tracing
allure_results_dir=allure-results
browser_state_file=browser-state.json
ui_coverage_apps=[
    {
        "key": "ui-course",
        "url": "https://nikita-filonov.github.io/qa-automation-engineer-ui-course/#/auth/login",
        "name": "UI Course",
        "tags": ["UI", "COURSES"],
        "repository": "https://github.com/Nikita-Filonov/qa-automation-engineer-ui-course"
    }
]
ui_coverage_results_dir=./coverage-results
ui_coverage_history_file=./coverage-history.json
ui_coverage_history_retention_limit=30
ui_coverage_html_report_file=./index.html
ui_coverage_json_report_file=./coverage-report.json
os_info=Windows, 11
python_version=3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)]